### ISSUE TITLE
Relaxing `max_pin` to `None`?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/rdma-core-feedstock#12]
Based on the discussion in issue ( https://github.com/conda-forge/ucx-split-feedstock/issues/143 ), it sounds like we are comfortable not having a `max_pin` for `rdma-core`

Currently the default `max_pin` is used, which is equivalent to `max_pin="x"`. IOW the maximum allow version is the next major version

https://github.com/conda-forge/rdma-core-feedstock/blob/1f2ee3bfe47659c36637cdf5b9191f2426efee68/recipe/meta.yaml#L17-L18

However given the high level compatibility from `rdma-core` and the frequency of major versions, wonder if we should use `max_pin=None`, meaning that there would be no `max_pin` for `rdma-core`

```diff
   run_exports:
-    - {{ pin_subpackage("rdma-core") }}
+    - {{ pin_subpackage("rdma-core", max_pin=None) }}
```

Thoughts?

**Comment by jakirkham** [comment]
cc @kkraus14 @pentschev

**Comment by kkraus14** [comment]
Based on https://github.com/linux-rdma/rdma-core/blob/master/Documentation/versioning.md it looks like they have a pretty strong commitment to ABI compatibility so I think we should be good to do this. +1 from me

**Comment by pentschev** [comment]
I agree with Keith that given there's strong commitment to ABI compatibility it should be mostly fine to remove the `max_pin`. However, I've recently seen cases where not having something equivalent to `max_pin` can be problematic, it's not even a conda issue but I wonder if something similar could occur here.

The situation I'm referring to above involves `dask-cuda` PyPI packages that didn't specify an upper bound of `dask` compatibility, so what happens today is if you're installing a large set of PyPI packages among which `dask-cuda` is included _without specifying the version_ (which intends to pick the latest), then an old version of `dask-cuda` will be installed instead. This happens because latest `dask-cuda` pins to a specific version of `dask` that is not the latest and some other package wants to pick latest `dask`, thus the solver ends up picking up a very old `dask-cuda` version that allows installing latest `dask`.

Could we fall under a similar problem here if we don't specify a `max_pin` _and_ one day `rdma-core` needs to break ABI?

**Comment by jakirkham** [comment]
> I imagine this is an issue that old versions of `dask-cuda` should have had a repodata patch to properly enforce their dask version compatibility?

Yep, which we did. For example ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/384 )

If we are seeing other issues still, let's report them in a new issue with enough details to reproduce them

> If one day `rdma-core` needs to break ABI we'd submit a repodata patch to add an upper pin on all of the older versions and I don't think this would be a problem in practice.

Exactly

**Comment by pentschev** [comment]
That's good to hear. If we have ways to resolve such problems in the future I'm +1 for this too.

> If we are seeing other issues still, let's report them in a new issue with enough details to reproduce them

The issue I'm mentioning is related to PyPI packages only, I was only using that as an example, so nothing to be discussed here related to that.

**Comment by pentschev** [comment]
Opened #13 to set `max_pin=None`.
